# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nchat.proto\"+\n\x07\x43hatAsk\x12\x11\n\tSessionId\x18\x01 \x01(\t\x12\r\n\x05Query\x18\x02 \x01(\t\".\n\nChatAnswer\x12\x11\n\tSessionId\x18\x01 \x01(\t\x12\r\n\x05Reply\x18\x02 \x01(\tb\x06proto3'
)




_CHATASK = _descriptor.Descriptor(
  name='ChatAsk',
  full_name='ChatAsk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SessionId', full_name='ChatAsk.SessionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Query', full_name='ChatAsk.Query', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=57,
)


_CHATANSWER = _descriptor.Descriptor(
  name='ChatAnswer',
  full_name='ChatAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SessionId', full_name='ChatAnswer.SessionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Reply', full_name='ChatAnswer.Reply', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['ChatAsk'] = _CHATASK
DESCRIPTOR.message_types_by_name['ChatAnswer'] = _CHATANSWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatAsk = _reflection.GeneratedProtocolMessageType('ChatAsk', (_message.Message,), {
  'DESCRIPTOR' : _CHATASK,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:ChatAsk)
  })
_sym_db.RegisterMessage(ChatAsk)

ChatAnswer = _reflection.GeneratedProtocolMessageType('ChatAnswer', (_message.Message,), {
  'DESCRIPTOR' : _CHATANSWER,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:ChatAnswer)
  })
_sym_db.RegisterMessage(ChatAnswer)


# @@protoc_insertion_point(module_scope)
