// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/websrv/websrv.proto

package micro_chatting_service_websrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Websrv service

func NewWebsrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Websrv service

type WebsrvService interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...client.CallOption) (*ChatResponse, error)
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Websrv_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Websrv_PingPongService, error)
}

type websrvService struct {
	c    client.Client
	name string
}

func NewWebsrvService(name string, c client.Client) WebsrvService {
	return &websrvService{
		c:    c,
		name: name,
	}
}

func (c *websrvService) Chat(ctx context.Context, in *ChatRequest, opts ...client.CallOption) (*ChatResponse, error) {
	req := c.c.NewRequest(c.name, "Websrv.Chat", in)
	out := new(ChatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websrvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Websrv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websrvService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Websrv_StreamService, error) {
	req := c.c.NewRequest(c.name, "Websrv.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &websrvServiceStream{stream}, nil
}

type Websrv_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type websrvServiceStream struct {
	stream client.Stream
}

func (x *websrvServiceStream) Close() error {
	return x.stream.Close()
}

func (x *websrvServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *websrvServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *websrvServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *websrvServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *websrvService) PingPong(ctx context.Context, opts ...client.CallOption) (Websrv_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Websrv.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &websrvServicePingPong{stream}, nil
}

type Websrv_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type websrvServicePingPong struct {
	stream client.Stream
}

func (x *websrvServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *websrvServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *websrvServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *websrvServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *websrvServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *websrvServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Websrv service

type WebsrvHandler interface {
	Chat(context.Context, *ChatRequest, *ChatResponse) error
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Websrv_StreamStream) error
	PingPong(context.Context, Websrv_PingPongStream) error
}

func RegisterWebsrvHandler(s server.Server, hdlr WebsrvHandler, opts ...server.HandlerOption) error {
	type websrv interface {
		Chat(ctx context.Context, in *ChatRequest, out *ChatResponse) error
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Websrv struct {
		websrv
	}
	h := &websrvHandler{hdlr}
	return s.Handle(s.NewHandler(&Websrv{h}, opts...))
}

type websrvHandler struct {
	WebsrvHandler
}

func (h *websrvHandler) Chat(ctx context.Context, in *ChatRequest, out *ChatResponse) error {
	return h.WebsrvHandler.Chat(ctx, in, out)
}

func (h *websrvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.WebsrvHandler.Call(ctx, in, out)
}

func (h *websrvHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.WebsrvHandler.Stream(ctx, m, &websrvStreamStream{stream})
}

type Websrv_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type websrvStreamStream struct {
	stream server.Stream
}

func (x *websrvStreamStream) Close() error {
	return x.stream.Close()
}

func (x *websrvStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *websrvStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *websrvStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *websrvStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *websrvHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.WebsrvHandler.PingPong(ctx, &websrvPingPongStream{stream})
}

type Websrv_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type websrvPingPongStream struct {
	stream server.Stream
}

func (x *websrvPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *websrvPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *websrvPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *websrvPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *websrvPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *websrvPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
