// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/website/website.proto

package go_micro_service_website

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Website service

func NewWebsiteEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Website service

type WebsiteService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Website_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Website_PingPongService, error)
}

type websiteService struct {
	c    client.Client
	name string
}

func NewWebsiteService(name string, c client.Client) WebsiteService {
	return &websiteService{
		c:    c,
		name: name,
	}
}

func (c *websiteService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Website.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Website_StreamService, error) {
	req := c.c.NewRequest(c.name, "Website.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &websiteServiceStream{stream}, nil
}

type Website_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type websiteServiceStream struct {
	stream client.Stream
}

func (x *websiteServiceStream) Close() error {
	return x.stream.Close()
}

func (x *websiteServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *websiteServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *websiteServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *websiteServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *websiteService) PingPong(ctx context.Context, opts ...client.CallOption) (Website_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Website.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &websiteServicePingPong{stream}, nil
}

type Website_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type websiteServicePingPong struct {
	stream client.Stream
}

func (x *websiteServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *websiteServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *websiteServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *websiteServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *websiteServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *websiteServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Website service

type WebsiteHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Website_StreamStream) error
	PingPong(context.Context, Website_PingPongStream) error
}

func RegisterWebsiteHandler(s server.Server, hdlr WebsiteHandler, opts ...server.HandlerOption) error {
	type website interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Website struct {
		website
	}
	h := &websiteHandler{hdlr}
	return s.Handle(s.NewHandler(&Website{h}, opts...))
}

type websiteHandler struct {
	WebsiteHandler
}

func (h *websiteHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.WebsiteHandler.Call(ctx, in, out)
}

func (h *websiteHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.WebsiteHandler.Stream(ctx, m, &websiteStreamStream{stream})
}

type Website_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type websiteStreamStream struct {
	stream server.Stream
}

func (x *websiteStreamStream) Close() error {
	return x.stream.Close()
}

func (x *websiteStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *websiteStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *websiteStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *websiteStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *websiteHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.WebsiteHandler.PingPong(ctx, &websitePingPongStream{stream})
}

type Website_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type websitePingPongStream struct {
	stream server.Stream
}

func (x *websitePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *websitePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *websitePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *websitePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *websitePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *websitePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
