app:
  mysql:
    enabled: true
    migrate: true
    url: 127.0.0.1:3306
    dbname: chat_db
    name: root
    psw: yourpassword
    maxIdleConnection: 100
    maxOpenConnection: 130
    connMaxLifetime: 100
