// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/web/web.proto

package micro_chatting_service_web

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Web service

func NewWebEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Web service

type WebService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Web_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Web_PingPongService, error)
}

type webService struct {
	c    client.Client
	name string
}

func NewWebService(name string, c client.Client) WebService {
	return &webService{
		c:    c,
		name: name,
	}
}

func (c *webService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Web.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Web_StreamService, error) {
	req := c.c.NewRequest(c.name, "Web.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &webServiceStream{stream}, nil
}

type Web_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type webServiceStream struct {
	stream client.Stream
}

func (x *webServiceStream) Close() error {
	return x.stream.Close()
}

func (x *webServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webService) PingPong(ctx context.Context, opts ...client.CallOption) (Web_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Web.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &webServicePingPong{stream}, nil
}

type Web_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type webServicePingPong struct {
	stream client.Stream
}

func (x *webServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *webServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *webServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *webServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Web service

type WebHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Web_StreamStream) error
	PingPong(context.Context, Web_PingPongStream) error
}

func RegisterWebHandler(s server.Server, hdlr WebHandler, opts ...server.HandlerOption) error {
	type web interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Web struct {
		web
	}
	h := &webHandler{hdlr}
	return s.Handle(s.NewHandler(&Web{h}, opts...))
}

type webHandler struct {
	WebHandler
}

func (h *webHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.WebHandler.Call(ctx, in, out)
}

func (h *webHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.WebHandler.Stream(ctx, m, &webStreamStream{stream})
}

type Web_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type webStreamStream struct {
	stream server.Stream
}

func (x *webStreamStream) Close() error {
	return x.stream.Close()
}

func (x *webStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *webHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.WebHandler.PingPong(ctx, &webPingPongStream{stream})
}

type Web_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type webPingPongStream struct {
	stream server.Stream
}

func (x *webPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *webPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *webPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
