// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mache/mache.proto

package micro_chatting_mache

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatAsk struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=Query,proto3" json:"Query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatAsk) Reset()         { *m = ChatAsk{} }
func (m *ChatAsk) String() string { return proto.CompactTextString(m) }
func (*ChatAsk) ProtoMessage()    {}
func (*ChatAsk) Descriptor() ([]byte, []int) {
	return fileDescriptor_016b66660ba662b3, []int{0}
}

func (m *ChatAsk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatAsk.Unmarshal(m, b)
}
func (m *ChatAsk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatAsk.Marshal(b, m, deterministic)
}
func (m *ChatAsk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatAsk.Merge(m, src)
}
func (m *ChatAsk) XXX_Size() int {
	return xxx_messageInfo_ChatAsk.Size(m)
}
func (m *ChatAsk) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatAsk.DiscardUnknown(m)
}

var xxx_messageInfo_ChatAsk proto.InternalMessageInfo

func (m *ChatAsk) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ChatAsk) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ChatAnswer struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Reply                string   `protobuf:"bytes,2,opt,name=Reply,proto3" json:"Reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatAnswer) Reset()         { *m = ChatAnswer{} }
func (m *ChatAnswer) String() string { return proto.CompactTextString(m) }
func (*ChatAnswer) ProtoMessage()    {}
func (*ChatAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_016b66660ba662b3, []int{1}
}

func (m *ChatAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatAnswer.Unmarshal(m, b)
}
func (m *ChatAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatAnswer.Marshal(b, m, deterministic)
}
func (m *ChatAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatAnswer.Merge(m, src)
}
func (m *ChatAnswer) XXX_Size() int {
	return xxx_messageInfo_ChatAnswer.Size(m)
}
func (m *ChatAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_ChatAnswer proto.InternalMessageInfo

func (m *ChatAnswer) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ChatAnswer) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatAsk)(nil), "micro.chatting.mache.ChatAsk")
	proto.RegisterType((*ChatAnswer)(nil), "micro.chatting.mache.ChatAnswer")
}

func init() { proto.RegisterFile("proto/mache/mache.proto", fileDescriptor_016b66660ba662b3) }

var fileDescriptor_016b66660ba662b3 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0x4c, 0xce, 0x48, 0x85, 0x90, 0x7a, 0x60, 0x11, 0x21, 0x91, 0xdc, 0xcc,
	0xe4, 0xa2, 0x7c, 0xbd, 0xe4, 0x8c, 0xc4, 0x92, 0x92, 0xcc, 0xbc, 0x74, 0x3d, 0xb0, 0x9c, 0x92,
	0x2d, 0x17, 0xbb, 0x73, 0x46, 0x62, 0x89, 0x63, 0x71, 0xb6, 0x90, 0x0c, 0x17, 0x67, 0x70, 0x6a,
	0x71, 0x71, 0x66, 0x7e, 0x9e, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x42, 0x40,
	0x48, 0x84, 0x8b, 0x35, 0xb0, 0x34, 0xb5, 0xa8, 0x52, 0x82, 0x09, 0x2c, 0x03, 0xe1, 0x28, 0x39,
	0x70, 0x71, 0x81, 0xb5, 0xe7, 0x15, 0x97, 0xa7, 0x16, 0x11, 0x36, 0x21, 0x28, 0xb5, 0x20, 0x07,
	0x6e, 0x02, 0x98, 0x93, 0xc4, 0x06, 0x76, 0x9d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x28,
	0x78, 0xd0, 0xb8, 0x00, 0x00, 0x00,
}
